### PR TITLE
Reorganize sources more like Python module

### PR DESCRIPTION
**Pull request by maedoc**
I'd like to reorganize a little further:

After looking at the Pegasus DAX API, I think it makes sense to move completely to using it. This implies unifying what was under `engine` into the Python module, and moving the Python module into the root of the repo. I'll start converting the Bash scripts to DAX API, including the pipeline steps. I think it makes sense to have dax generators which wrap specific CLI programs and higher level daxgen for logical steps. In all cases, they can be defined in `bnm.recon.daxgen.*` modules.

I'd like to pin the Pegasus Python module in use to a sepcific version, (along with other dependencies), and `git submodule` is a standard way of doing that, allowing us to coordinate our versioning with upstream but without having to store all the upstream code in our own repo. MRtrix, OpenMEEG and MNE-Python are quick moving projects where this would be  helpful. Others like FS, FSL & MNE-C are not feasible or possible.

I also see configuration as a testing or site-specific issue, so there's a separate directory there, though in some cases, it could make sense to have a function or templates to assist in generating such configurations.

The setting up notes are already out of date in some cases, but my hope is that we can keep it up to date for at least one Linux distribution. The NOTES.md is also out of date, but hope that once the workflows are better transcribed in the daxgen code, this will improve.

I also removed the DAX and DOT generated files from version control and added these extensions to the `.gitignore` as I see them as build artifacts, but there's a case to be made for examples or testing maybe.

The `KEY_FOO = "foo"` pattern looks really strange in (scientific) Python, if we could use e.g. the enum34 package or some alternative I would :heart: it.

@liadomide comments?

### CODE REVIEW

**Comment by maedoc** [comment]
Also you guys need to merge you changes, preferably after this PR is merged. You can `git rebase` on this branch to see what that would entail, or I can pull those changes myself into this PR? What do you thinkg @liadomide @dionperd ?

**Comment by dionperd** [comment]
I hardly understood anything.

Just don't make it too hard for me to interact with it!

Also, I don't know if it makes sense to substitute bash scripts with 
something else I don't understand before I have finished with the 
algorithm, and before the pipeline workflow is in an initial working 
condition.

Anyway, you guys know better...

**Comment by dionperd** [comment]
git rebase is a language I don't understand.

**Comment by maedoc** [comment]
@dionperd the `git rebase` comment was not meant for you :stuck_out_tongue_winking_eye: 

Keep writing your Bash scripts, and we'll put them in the `bin` folder, ie. the folder that should be added to the `PATH` env var. We can simply wrap these scripts in daxgen as commands initially, and later on move the logic out of the script and into the daxgen module. The parts which are Python functions can go into the `bnm.recon.algo` or similar.

**Comment by liadomide** [comment]
On long and medium term, I think that switching to dax api for describing the steps is a good direction. On short term, I think it is ok to keep the bash scripts as well, at least until we are all comfortable with the engine usage. As soon as the bash scripts will become outdated, we could drop them completely, as I don't think we should loose time in maintaining two "languages".

The workflow engine indeed requires a configuration part (patient and machine specific). The location you propose for these, seems appropriate.

`output` (like .dax, .dot or .png) should definitely not be kept long term in the repo. Currently there are exactly for what you mentioned (illustration), so their final location should be somewhere under `docs`, together with some comments.

**Pull request merged**
