### PR TITLE
Integrate DenisWorkflow

### PR DESCRIPTION
**Pull request by maedoc**
This PR is to integrate the DenisWorkflow brnach in to master, since it diverged quite a bit. Merging that branch directly on master would be difficult.

I renamed `snapshot` to `qc` because that package is concerned with quality control, not just making screenshots.

The new Python code is added, and I'll start looking at the other stuff as well.
- [x] - `pegasus` and `snapshot` Python packages
- [x] - `snapshot.sh` runner script
- [ ] - Denis' new and updated scripts & Python

### CODE REVIEW

**Comment by liadomide** [comment]
I think it is ok to do a one-time manual integration of the DenisBranch into master.
The only small disadvantage that I see is the loss of history, but this is ok, considering the troubles in merging.

**Comment by maedoc** [comment]
I know, I hope we avoid this in the future. There might be a way with git subtree to keep history; I'll take a look.

**Comment by maedoc** [comment]
@dionperd I reviewed your scripts and see you didn't use or change the new Python package, just your copies of `reconutils.py` and `snapshots.py`. Is that accurate?

To complete this merge, I think we can 
- move Denis' scripts to the bin/ folder
- move the Python modules into the `bnm` package and update the imports

After that, it would be helpful to make an effort to use the typical feature PR->master workflow.

**Comment by liadomide** [comment]
ok from my p.o.v.

**Comment by maedoc** [comment]
I'm closing in deference to #8

**Pull request closed without merging**
