### PR TITLE
Repository structure proposal

### PR DESCRIPTION
**Pull request by liadomide**
Hi,
What do you think about having the following as structure on https://github.com/ins-amu/bnm-recon-tools master branch ?

```
#Git repo
bnm-recon-tools
	# Files
	README.md
	LICENSE # Which one? Apache? BSD ?
	.gitignore
	# Subfolders
	docs
		# with the current content
	setup-vm
		# with the current content
	pipeline-steps
		# with the current files, except *.pyx, .DS-Store, *.log
		config.sh
		reconAll.sh
		resamp-anat.sh
		…….
	python	
		setup.py
		bnm.recon…… #all python code for this tool, including unit-tests
	engine	
		# Pegasus files (current C-pegasus folder)

```

### CODE REVIEW

**Comment by maedoc** [comment]
:+1:, and :+1: for Apache license.

:question: Do Pegasus files duplicate functionality of `pipeline-steps/*.sh` or wrap them?

**Comment by liadomide** [comment]
About Pegasus files:
- first I thought they will be wrapping the `pipeline-steps/*.sh`
- now I like more and more the idea (which I think was incepted by you in one of the talks) to make the DAG steps smaller (e.g. `recon-all`, `mri_convert`) 

If the second alternative remains, then Pegasus files will be duplicating the functionality in `pipeline-steps/*.sh`.

**Comment by maedoc** [comment]
If a Pegasus step runner isn't too difficult to cumbersome to use informally for testing, then moving steps fully to a Pegasus format isn't a problem, especially if they're written against the Python/Java API which could be retargeted as required.

**Comment by maedoc** [comment]
ready to merge?

**Comment by liadomide** [comment]
From my perspective, ready.

**Comment by dionperd** [comment]
OK from my part!

**Pull request merged**
